---
# RabbitMQ Message Queue
# For async task processing

apiVersion: v1
kind: ServiceAccount
metadata:
  name: rabbitmq
  namespace: data
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: data
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: "admin"
  RABBITMQ_DEFAULT_PASS: "changeme-strong-password"  # Change this!
  RABBITMQ_ERLANG_COOKIE: "changeme-erlang-cookie"   # Change this!
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: data
data:
  rabbitmq.conf: |
    # RabbitMQ Configuration
    loopback_users.guest = false
    listeners.tcp.default = 5672
    management.tcp.port = 15672
    
    # Clustering
    cluster_formation.peer_discovery_backend = kubernetes
    cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
    cluster_formation.k8s.address_type = hostname
    cluster_formation.node_cleanup.interval = 30
    cluster_formation.node_cleanup.only_log_warning = true
    cluster_partition_handling = autoheal
    
    # Memory and disk limits
    vm_memory_high_watermark.relative = 0.6
    disk_free_limit.absolute = 2GB
    
    # Message TTL (24 hours default)
    default_message_ttl = 86400000
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: data
  labels:
    app: rabbitmq
spec:
  type: ClusterIP
  ports:
  - name: amqp
    port: 5672
    targetPort: 5672
  - name: management
    port: 15672
    targetPort: 15672
  selector:
    app: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-headless
  namespace: data
  labels:
    app: rabbitmq
spec:
  clusterIP: None
  ports:
  - name: amqp
    port: 5672
  - name: management
    port: 15672
  selector:
    app: rabbitmq
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: data
  labels:
    app: rabbitmq
spec:
  serviceName: rabbitmq-headless
  replicas: 3
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "15692"
    spec:
      serviceAccountName: rabbitmq
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        fsGroup: 999
      containers:
      - name: rabbitmq
        image: rabbitmq:3.12-management-alpine
        ports:
        - name: amqp
          containerPort: 5672
        - name: management
          containerPort: 15672
        - name: prometheus
          containerPort: 15692
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 2000m
            memory: 4Gi
        envFrom:
        - secretRef:
            name: rabbitmq-credentials
        env:
        - name: RABBITMQ_NODENAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: K8S_SERVICE_NAME
          value: rabbitmq-headless
        - name: RABBITMQ_USE_LONGNAME
          value: "true"
        livenessProbe:
          exec:
            command:
            - rabbitmq-diagnostics
            - -q
            - ping
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          exec:
            command:
            - rabbitmq-diagnostics
            - -q
            - check_port_connectivity
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
        volumeMounts:
        - name: data
          mountPath: /var/lib/rabbitmq
        - name: config
          mountPath: /etc/rabbitmq/rabbitmq.conf
          subPath: rabbitmq.conf
      volumes:
      - name: config
        configMap:
          name: rabbitmq-config
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbitmq-management
  namespace: data
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - rabbitmq.yourdomain.com
    secretName: rabbitmq-tls
  rules:
  - host: rabbitmq.yourdomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rabbitmq
            port:
              number: 15672
